fail_fast: true
default_install_hook_types:
  - commit-msg
  - pre-commit
default_stages:
  - pre-commit
  - manual
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff-format
      - id: ruff
        args:
          - "--config"
          - ".ruff.toml"
          - "--fix"
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.393
    hooks:
      - id: pyright
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
        args: ["--config", ".commitlintrc.yaml"]
