version: "3.8"

services:
  frontend:
    image: giodefa996/frontend:0.0.1
    container_name: frontend-app
    ports:
      - "8501:8501"
    extra_hosts:
      - "localhost:172.17.0.1"
    depends_on:
      - backend
    volumes:
      - ./certs/cert.pem:/usr/local/lib/python3.12/site-packages/src/certs/cert.pem:ro
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - CERT_FILE_PATH=${CERT_FILE_PATH}
  backend:
    image: giodefa996/backend:0.0.1
    container_name: backend-api
    expose:
      - "8000"
    depends_on:
      - database
      - storage
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - PDF_BATCH_SIZE=${PDF_BATCH_SIZE}
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    restart: always
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    ports:
      - "${AZURITE_BLOB_PORT}:10000" # Blob service
      - "${AZURITE_QUEUE_PORT}:10001" # Queue service
      - "${AZURITE_TABLE_PORT}:10002" # Table service
    volumes:
      - azurite_data:/data

volumes:
  db_data:
  azurite_data:
